version: '2'
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      USER: 1000

  beanstalkd:
    image: schickling/beanstalkd
    hostname: beanstalkd
    links:
      - redis
      - mysql
    ports:
      - "11300:11300"

  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

  web:
    image: lbanchio/docker-php-nginx
    hostname: dev
    links:
      - redis
      - mysql
      - beanstalkd
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/sites-available
      - ../:/var/www
    environment:
      TZ: "America/Argentina/Cordoba"
      COMPOSER_CACHE_DIR: /var/www/.composer
      COMPOSER_HOME: /var/www/.composer
